Add Previous Source Ids to Snapshot Metadata
rasmus/EventFlow pull request #808
Opened 2020-11-25 03:17 UTC by WardenUnleashed

Fixes #799 

This allows the aggregate to correctly throw duplicate command exceptions on throw.

2020-11-25 03:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/eventflow/EventFlow?pullRequest=808) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/eventflow/EventFlow?pullRequest=808) before we can accept your contribution.<br/><hr/>**Andrew Johnson** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/eventflow/EventFlow?pullRequest=808) it.</sub>

2020-12-04 07:02 UTC, rasmus commented
@WardenUnleashed There's several failing tests. Could you have a look?

2020-12-05 19:08 UTC, WardenUnleashed commented
Ill try and tackle that this weekend!

2020-12-17 00:01 UTC, WardenUnleashed commented
@rasmus Tests should be fixed! Sorry it took so long, I was on vacation and didn't get a chance to finish this sooner!

2020-12-18 06:45 UTC, rasmus commented on Source/EventFlow/Aggregates/AggregateRoot.cs
> +        protected void SetPreviousSourceIds(IEnumerable<ISourceId> sourceIds)
Should be renamed to `AddPreviousSourceIds`

2020-12-18 06:46 UTC, rasmus commented on Source/EventFlow/Aggregates/AggregateRoot.cs
> +            var sourceIds = domainEvents.Where(e => e.Metadata.ContainsKey(MetadataKeys.SourceId)).Select(e => e.Metadata.SourceId);
Add some line breaks before the "." to make it more readable like this

```csharp
var sourceIds = domainEvents
  .Where(e => e.Metadata.ContainsKey(MetadataKeys.SourceId))
  .Select(e => e.Metadata.SourceId)
```

2020-12-18 06:49 UTC, rasmus commented on Source/EventFlow/Snapshots/SnapshotMetadata.cs
> +                    Enumerable.Empty<ISourceId>() :
Add a static readonly member that's an empty `IReadOnlyCollection<ISourceId>` and return that instead of doing a `ToList()` on an empty enumerable

2020-12-18 06:50 UTC, rasmus commented on Source/EventFlow/Snapshots/SnapshotMetadata.cs
> +                    json.Split(',').Select(sourceId => new SourceId(sourceId))).ToList().AsReadOnly();
Add the `StringSplitOptions.RemoveEmptyEntries` to the `.Split`

2020-12-18 06:51 UTC, rasmus requested changes
Thanks for the PR ❤️  it lacks some tests that verifies the addition though.

2020-12-18 06:52 UTC, rasmus commented
I moved the PR to `develop-v0`. I'll delete the branch when I'm able. Currently GitHub doesn't allow it as there's open PRs on it. Hopefully I'll get the time during the holidays to do some cleanup

2020-12-28 23:03 UTC, WardenUnleashed commented
@rasmus I revised the MR with the feedback given. Let me know how it looks.

Last thing to wrap this up would be to add an integration test that specifically tests the bug's use case!

2021-01-11 13:05 UTC, rasmus approved these changes

2021-01-11 13:05 UTC, merged